[23기 한승훈] ADD : 로그인,회원가입,카카오코드수령후처리로직
wecode-bootcamp-korea/23-2nd-caseT-Fany-backend pull request #2
Opened 2021-08-19 06:07 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입, 로그인, 프론트에서 카카오 토큰 처리 로직
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-회원가입, 로그인, 프론트에서 카카오에서 코드 수령 후 백엔드에게 코드 전달 시 처리 코드 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-19 07:23 UTC, Samdaso-o commented
![스크린샷 2021-08-19 오후 4 19 14](https://user-images.githubusercontent.com/76812640/130025770-3c33a12f-c62f-470b-972b-cd7868611fcb.png)
프론트에서 코드 수령 후 백엔드에서 토큰 처리 완료한 코드입니다

2021-08-20 01:42 UTC, Kang-kyunghun requested changes

2021-08-20 01:42 UTC, Kang-kyunghun commented on users/views.py
> +                token = jwt.encode({'id':User.objects.get(email=email).id}, SECRET_KEY, algorithm=const_algorithm)
```suggestion
            user = User.objects.get(email=email)
            
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                token = jwt.encode({'id' : user.id}, SECRET_KEY, algorithm=const_algorithm)
```
user를 미리 get을 한 뒤에 사용하면 각독성이 훨씬 올라가고, 중복으로 데이터베이스에 쿼리를 요청하지 않습니다.

2021-08-20 01:42 UTC, Kang-kyunghun commented on users/views.py
> +class KakaoSignInCallBackView(View):
```suggestion
class KakaoSignInCallBackView(View):
```
callback이라고 붙인 이유를 코멘트로 남겨주세요.

2021-08-20 01:42 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({"message" : "INVALID_TOKEN"}, status = 400)
모든 except는 코드 맨 아래로 내려서 가독성을 높여주세요.

2021-08-20 01:42 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({"Token" : token}, status = 200)
get_or_create를 사용해 보세요.

2021-08-20 01:42 UTC, Kang-kyunghun commented on users/views.py
> +            )
전반적인 소셜로그인 부분은 만나서 이야기 해봐요

2021-08-20 01:52 UTC, Samdaso-o commented on users/views.py
> +class KakaoSignInCallBackView(View):
프론트에서 코드를 받은 뒤 그 코드를 저희 백엔드 쪽에서 수령하여 토큰을 발행하고 정보를 얻는다는 점에서 callback이라는 이름이 맞는거 같아 붙이게 되었습니다 ㅎ

2021-08-20 01:53 UTC, Samdaso-o commented on users/views.py
> +            return JsonResponse({"message" : "INVALID_TOKEN"}, status = 400)
넵!

2021-08-20 02:35 UTC, Samdaso-o commented on users/views.py
> +            return JsonResponse({"Token" : token}, status = 200)
넵 ㅎㅎ

2021-08-20 02:35 UTC, Samdaso-o commented on users/views.py
> +            )
넵! 저 질문도 잇습니다 ㅠㅠ

2021-08-20 04:18 UTC, Samdaso-o commented on users/views.py
> +                token = jwt.encode({'id':User.objects.get(email=email).id}, SECRET_KEY, algorithm=const_algorithm)
넵 ㅎㅎ

2021-08-22 07:43 UTC, Kang-kyunghun requested changes

2021-08-22 07:43 UTC, Kang-kyunghun commented on users/views.py
> +            token = jwt.encode({"email" : email}, SECRET_KEY, algorithm=const_algorithm)
email 보다는 pk(id)로 만드는 것이 해당 데이터를 더 명확히 가르키게 됩니다.

2021-08-22 07:44 UTC, Samdaso-o commented on users/views.py
> +            token = jwt.encode({"email" : email}, SECRET_KEY, algorithm=const_algorithm)
넵 수정하겟습니다 ㅎ

2021-08-23 01:38 UTC, Kang-kyunghun commented
LGTM~!

2021-08-23 01:38 UTC, merged