[23기 한승훈] review C.R.U.D기능
wecode-bootcamp-korea/23-2nd-caseT-Fany-backend pull request #5
Opened 2021-08-21 07:19 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 리뷰 C.R.U.D
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 리뷰 crud, image file을 form-data로 받기 위해 post문에 생성과 업데이트를 동시에 진행하였습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- patch랑 put은 form-data형식을 사용할 시 받은 모든 데이터가 None으로 출력되던데, 이 오류를 해결할 수 있는 방법이 있을까요?
- get요청시 image value값으로 url이 아닌 이미지 파일 자체를 출력하는 방법이 있나요..?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 01:46 UTC, Kang-kyunghun requested changes

2021-08-23 01:46 UTC, Kang-kyunghun commented on reviews/views.py
> +            user       = request.user.id
이미지 파일을 직접 DB에 저장하는 것이 아니고, 파일은 S3같은 클라우드 서비스에 저장 후에 저장한 곳의 URL을 str로 DB에 저장해 주셔야 합니다.

2021-08-23 01:46 UTC, Kang-kyunghun commented on reviews/views.py
> +    def get(self, request):
리뷰 1개를 get하는 api로 보이는데, 혹시 상품에 대한 전체 리뷰는 상품 상세에서 같이 가져오나요?

2021-08-23 01:46 UTC, Kang-kyunghun commented on reviews/views.py
> +            review_id = request.GET.get('review_id')
/reviews/<review_id> 같이 path parameter로 사용하시는 것이 조금 더 RESTful 할 것 같습니다.

2021-08-23 01:46 UTC, Kang-kyunghun commented on reviews/views.py
> +    def delete(self, request):
이 부분도 /reviews/<review_id> 같이 path parameter로 사용하시는 것이 조금 더 RESTful 할 것 같습니다.

2021-08-23 01:46 UTC, Kang-kyunghun commented on reviews/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=404)
키에러 같은 경우 보통 status code로 400을 사용합니다.

2021-08-23 01:46 UTC, Kang-kyunghun commented on reviews/views.py
> +                return JsonResponse({'MESSAGE':'NOT_EXISTS'}, status=400)
Dose Not Exists 같은 경우 보통 status code로 404을 사용합니다.

여러 status code들이 주로 어떤 상화에서 사용 되는지 공부해 보시면 좋을 것 같아요!

2021-08-24 08:48 UTC, Samdaso-o commented on reviews/views.py
> +            user       = request.user.id
넵 수정완료했습니다

2021-08-24 08:49 UTC, Samdaso-o commented on reviews/views.py
> +    def get(self, request):
넵 맞습니다 상세에서 같이 가져옵니다!

2021-08-24 08:49 UTC, Samdaso-o commented on reviews/views.py
> +            review_id = request.GET.get('review_id')
넵 변경완료했습니다

2021-08-24 08:49 UTC, Samdaso-o commented on reviews/views.py
> +    def delete(self, request):
넵! ㅎㅎ

2021-08-24 08:49 UTC, Samdaso-o commented on reviews/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=404)
넵!

2021-08-24 08:50 UTC, Samdaso-o commented on reviews/views.py
> +                return JsonResponse({'MESSAGE':'NOT_EXISTS'}, status=400)
넵 좀 더 공부해보도록 하겟습니다 ㅎ

2021-08-25 00:56 UTC, Kang-kyunghun requested changes

2021-08-25 00:56 UTC, Kang-kyunghun commented on reviews/tests.py
> +
테스트 케이스에 json 결과도 같이 비교해 주세요.

2021-08-25 00:56 UTC, Kang-kyunghun commented on reviews/views.py
> +                    defaults={'text':text, 'score':score, 'image':'https://wecode-23-casetfany.s3.us-east-2.amazonaws.com/' + upload_key}
```suggestion
                    defaults = {
                        'text' :text, 
                        'score':score, 
                        'image':'https://wecode-23-casetfany.s3.us-east-2.amazonaws.com/' + upload_key
                    }
```
조금 더 가독성에 도움이 될 것 같아요

2021-08-25 02:09 UTC, Samdaso-o commented on reviews/tests.py
> +
넵!

2021-08-25 02:10 UTC, Samdaso-o commented on reviews/views.py
> +                    defaults={'text':text, 'score':score, 'image':'https://wecode-23-casetfany.s3.us-east-2.amazonaws.com/' + upload_key}
넵!

2021-08-26 01:00 UTC, Kang-kyunghun requested changes

2021-08-26 01:00 UTC, Kang-kyunghun commented on reviews/views.py
> +            review.delete()
```suggestion
        if review.image_url:
            s3_resource  = boto3.resource(
                        's3',
                        aws_access_key_id     = AWS_S3_ACCESS_KEY_ID,
                        aws_secret_access_key = AWS_S3_SECRET_ACCESS_KEY,
                    )
            bucket = s3_resource.Bucket(name = AWS_STORAGE_BUCKET_NAME)
            bucket.delete_objects(key = review.key)
            
        review.delete()
```

2021-08-26 01:00 UTC, Kang-kyunghun commented on reviews/views.py
> +                return JsonResponse({'MESSAGE':'SUCCESS'},status = 201)
이 부분은 만나서 이야기 해봐요

2021-08-26 04:21 UTC, Samdaso-o commented on reviews/views.py
> +                return JsonResponse({'MESSAGE':'SUCCESS'},status = 201)
넵 ㅎ 좀 더 코드를 축약해서 pr 올려보앗습니당

2021-08-26 06:22 UTC, Kang-kyunghun commented
LGTM~~~!!!

2021-08-26 06:47 UTC, merged