[23기 김훈태] 상품리스트 페이지
wecode-bootcamp-korea/23-2nd-caseT-Fany-backend pull request #6
Opened 2021-08-21 16:15 UTC by kim-hoontae

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 filtering, sorting, searching
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-22 07:51 UTC, Kang-kyunghun requested changes

2021-08-22 07:51 UTC, Kang-kyunghun commented on products/views.py
> +            'color'      : [product_option.color.name for product_option in product.productoption_set.all()][0],
```suggestion
            'color'      : [product_option.color.name for product_option in product.productoption_set.all()][0],
```
index을 상요한 이유를 코멘트로 남셔주세요.

2021-08-22 07:51 UTC, Kang-kyunghun commented on products/views.py
> +            .order_by(sort_name.get(sorting,'id'))[offset:limit]
```suggestion
        products = Product.objects.filter(filters)\
                                  .annotate(sales = Sum('productoption__sales'))\
                                  .order_by(sort_name.get(sorting,'id'))[offset:limit]
```
다음과 같이 수정하는 것이 가독성에 더 좋을 것  같습니다.

2021-08-22 07:52 UTC, Kang-kyunghun commented
백엔드 개발자는 페이지가 아닌 어떤 자원에 대한 api인가를 생각하셔야 합니다.

2021-08-22 07:54 UTC, kim-hoontae commented on products/views.py
> +            .order_by(sort_name.get(sorting,'id'))[offset:limit]
넵 수정 하겠습니다.

2021-08-22 08:18 UTC, kim-hoontae commented on products/views.py
> +            'color'      : [product_option.color.name for product_option in product.productoption_set.all()][0],
product_option 테이블에 size_id와 color_id 컬럼이 있는데 size는 3개 이고 color는 1개로 되어있는 구조라서 결과값에 동일한 color 3개가 표현되서 하나의 값만 가져오기위해 사용했습니다.

2021-08-23 08:20 UTC, Kang-kyunghun commented on test.py
> +        print('===========================')
print 제거해 주세요.

2021-08-23 08:20 UTC, Kang-kyunghun commented on test.py
> +from products.models import *
```suggestion
from products.models import Category, SubCategoy....
```
실제 코드에서는 *을 지양해 주세요.

2021-08-23 08:20 UTC, Kang-kyunghun commented on products/views.py
> +            'color'      : [product_option.color.name for product_option in product.productoption_set.all()][0],
이 부분은 한 번 같이 볼게요!!

2021-08-23 10:09 UTC, kim-hoontae commented on test.py
> +        print('===========================')
넵 바로 제거하겠습니다

2021-08-23 10:09 UTC, kim-hoontae commented on test.py
> +from products.models import *
넵 수정하겠습니다.

2021-08-23 11:05 UTC, Kang-kyunghun requested changes

2021-08-23 11:05 UTC, Kang-kyunghun commented on test.py
> +
테스트 코드에 json 결과를 비교하는 부분도 추가해 주세요.

2021-08-24 08:07 UTC, Kang-kyunghun commented
LGTM~~!!

2021-08-24 08:07 UTC, merged