[23기 한승훈] 커스텀 저장
wecode-bootcamp-korea/23-2nd-caseT-Fany-backend pull request #7
Opened 2021-08-23 02:42 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 커스텀 제품 저장
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 커스텀 제품 정보 받아서 저장, 장바구니에 정보 저장

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 51-53 Line 로직이 너무 긴거 같습니다..

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-24 01:39 UTC, Kang-kyunghun requested changes

2021-08-24 01:39 UTC, Kang-kyunghun commented on products/views.py
> +                quantity          = 1,
수량의 default 값을 줘서 하드코딩 한 부분을 줄이면 좋을 것 같습니다.

2021-08-24 01:39 UTC, Kang-kyunghun commented on products/views.py
> +            )
이 부분을 통으로 get_or_create을 이용해서 합칠 수 있을 것 같은데, 한 번 생각해보고 오후에 같이 이야기 해봐요

2021-08-24 01:40 UTC, Kang-kyunghun commented
다른 멘토님들과 토의를 한 결과 해당 View는 order app (또는 cart app)으로 이동하는 것이 맞을 것 같아요.

2021-08-24 08:51 UTC, Samdaso-o commented on products/views.py
> +            )
넵

2021-08-24 08:51 UTC, Samdaso-o commented on products/views.py
> +                quantity          = 1,
넵 ㅎ

2021-08-25 01:05 UTC, Kang-kyunghun requested changes

2021-08-25 01:05 UTC, Kang-kyunghun commented on carts/views.py
> +            product.sales = product.sales+1
```suggestion
            product.stock -= 1
            product.sales += 1
```

2021-08-25 01:05 UTC, Kang-kyunghun commented on carts/views.py
> +                cart_product.save()
```suggestion
            cart, cart_is_created = Cart.objects.get_or_create(
                user_id           = user.id, 
                custom_product_id = customproduct.id, 
                defaults           = {'quantity' : 1 }
            )
            
            if not cart_is_created:
                cart_product.quantity += 1
                cart_product.save()
```
cart에 추가하는 로직을 다음과 같이 바꿔도 될 것같은데 한 번 확인해 보세요.

2021-08-25 02:50 UTC, Samdaso-o commented on carts/views.py
> +            product.sales = product.sales+1
엇! 넵 ㅎ

2021-08-25 04:27 UTC, Samdaso-o commented on carts/views.py
> +                cart_product.save()
넵 !

2021-08-25 09:54 UTC, Kang-kyunghun commented
LGTM~~!!

2021-08-25 09:54 UTC, merged